export const ERROR_CODE = {
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INSUFFICIENT_POINTS: "INSUFFICIENT_POINTS",
  INSUFFICIENT_OWNERSHIP_QUANTITY: "INSUFFICIENT_OWNERSHIP_QUANTITY",
  SHOP_LISTING_SOLD_OUT: "SHOP_LISTING_SOLD_OUT",
  RANDOM_BOX_COOLDOWN: "RANDOM_BOX_COOLDOWN",
};
